language: android
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-34.0.0
    # The SDK version used to compile your project
    - android-34
  script:
    - ./gradlew clean build assembleFdroidBeta assembleFdroidRelease
before_script:
  - sudo apt-get install npm
  - sudo apt-get install nodejs-legacy
  - npm config set strict-ssl false  
  - sudo npm install uglify-js -g
  - chmod ug+x ./gradlew
  #- sed -i -e '/signingConfigs.debug/d' app/build.gradle

