language: android
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-28.0.2
    # The SDK version used to compile your project
    - android-26
  script:
    - ./gradlew clean build assembleFdroid
before_script:
  - sudo apt-get install npm
  - sudo apt-get install nodejs-legacy
  - npm config set strict-ssl false  
  - sudo npm install uglify-js -g

