language: android
before-script:
    - sudo apt-get -y install node-uglifyjs
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-28.0.2
    # The SDK version used to compile your project
    - android-26
  script:
    - ./gradlew clean build assembleFdroid
